import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Landing from "../Components/Landing";
import Sidebar from "../Components/Sidebar";
import Skills from "../Components/Skills";
import { useState, useEffect, useRef } from "react";
import Projects from "../Components/Projects";
import Contact from "../Components/Contact";
export default function Home() {
  const [navigator, setNavigator] = useState();
  const about = useRef(null);
  const skills = useRef(null);
  const projects = useRef(null);
  const contact = useRef(null);
  const [toggle, setToggle] = useState(false);
  useEffect(() => {
    if (window.innerWidth > 599) setToggle(true);
    else setToggle(false);
    window.addEventListener(
      "resize",
      () => {
        if (window.innerWidth > 599) setToggle(true);
        else setToggle(false);
      },
      []
    );
    switch (navigator) {
      case 0:
        about.current.scrollIntoView();
        break;
      case 1:
        skills.current.scrollIntoView();
        break;

      case 2:
        projects.current.scrollIntoView();
        break;
      case 3:
        contact.current.scrollIntoView();
        break;

      default: {
        // if (window.pageYOffset < window.innerHeight / 2) setNavigator(-1);
        break;
      }
    }
    setNavigator(-1);
  }, [navigator]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Wissem Rouabeh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar
        setNavigator={setNavigator}
        setToggle={setToggle}
        toggle={toggle}
      />
      <div className={styles.main}>
        <Landing
          setNavigator={setNavigator}
          ineref={about}
          setToggle={setToggle}
        />
        <Skills ineref={skills} setToggle={setToggle} />
        <Projects
          setNavigator={setNavigator}
          ineref={projects}
          setToggle={setToggle}
        />
        <Contact ineref={contact} setToggle={setToggle} />
      </div>
    </div>
  );
}
